repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: make fmt-check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: make clippy
        language: system
        types: [rust]
        pass_filenames: false
